controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

index:
  path: /
  controller: App\Controller\DefaultController::index

oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\SecurityBundle\Controller\TemplateController
